# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Create data frame of raster cells and the travel time between them
#'
#' @description Uses an Integer Matrix of the cells values in a raster
#' representation of a road network to determine the IDs of adjacent matrix or,
#' equivalently, raster cells and calculate the travel cost, quantified in
#' seconds, from the center of the first cell to the center of the second.
#'
#' @details The cell values in m should be integers and represent the road
#' speed limit in miles per hour. Cell values equal to 255 correspond to NODATA
#' (background / no road cell). cellSize is the resolution of the raster used
#' to extract m in native units, meters of feet. This function is called
#' internally by prepareGraph().
#'
#' @param m Integer Matrix
#' @param cellSize double
#' @param linearUnitFactor double
#'
#' @noRd
#'
#' @export
rcpp_buildNodeDF <- function(m, cellSize, linearUnitFactor, costType) {
    .Call(`_tRee2MillCost_rcpp_buildNodeDF`, m, cellSize, linearUnitFactor, costType)
}

